name: event_app # Replace with your actual project name
description: A new Flutter project for event-based communities.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Example SDK constraint

dependencies:
  flutter:
    sdk: flutter

  # Supabase integration
  supabase_flutter: ^2.0.0 # Check for the latest stable version

  # State Management
  flutter_riverpod: ^2.3.0 # Check for the latest stable version
  riverpod_annotation: ^2.1.0 # If using riverpod_generator

  # Utility packages
  intl: ^0.18.0 # For date/time formatting (latest is 0.19.x but 0.18 is common)
  # go_router: ^10.0.0 # Example if GoRouter is used for navigation (check latest)
  # http: ^1.0.0 # If direct HTTP calls are made outside of Supabase client

  # UI related
  cupertino_icons: ^1.0.2 # Default with Flutter projects

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0 # Recommended lints

  # Mocking for tests
  mockito: ^5.4.0 # Check for the latest stable version
  build_runner: ^2.4.0 # Check for the latest stable version

  # Riverpod testing utilities (if needed, often flutter_riverpod handles this)
  # riverpod_test: any # If specific testing utilities for riverpod are used

# flutter_native_splash: # Example for splash screen
# flutter_launcher_icons: # Example for app icons

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  // https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  //       - asset: fonts/TrajanPro.ttf
  //       - asset: fonts/TrajanPro_Bold.ttf
  //         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
